<a href="https://colab.research.google.com/github/danielduartt/Fundamentos-DataScience/blob/main/2_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
#Bibliotecas
import pandas as pd
from numpy.random import randn
import numpy as np

#_DataFrames:_

In [62]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
#A função randn criará uma matrix 5x4 de valores aleatórios seguindo uma dist normal
#Informo os indíces com o "index = ..."
#E as colunas com "columns = ..."
display(df)

          W         X         Y         Z
A  0.194534 -0.121365  0.745119 -0.725044
B -0.531893 -1.079807 -0.988132  1.425870
C -0.783987  0.254527 -1.996077 -0.110237
D  0.747088 -0.779894 -0.941424 -0.527928
E -0.218164  1.982982  1.039475  0.450998

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
#DataFrames possuem indíces e colunas, as Series possuem apenas indíces
#Cada colunas é uma série

#_Lendo e Salvando DataSets:_

In [ ]:
'''* lendo arquivos csv
pd.read_csv('diretório/xxxx.csv', sep = ',' ) o sep é o separador
  funções:
      df.head()
      df.tail() => 5 ultimas linhas
      df.describe()
      df.shape()

* lendo arquivos xlsx (excel)
pd.read_excel('diretório/xxxx.xlsx', sheet_name = 'Sheet1') # O sheet_name está relacionado a aba que vai ser lida
nesse caso o 'Sheet1' vai ler a primeira

df = pd.read_excel('diretório/xxxx.xlsx', sheet_name = 'Sheet1')

  - df.to_csv('diretório/nome.csv') => salvando o arquivo xlsx em um arquivo csv
obs: pode salvar em Excel tbm, com:
  - df2.to_excel('diretório/nome.xlsx')

* lendo arquivo html
pd.read_html('diretório/xxxx.html')

* lendo conteúdo do famoso (control + c)
pd.read_clip_board()'''

In [5]:
#Pegando tabelas da Web
'''

*bibliotecas necessárias:
  lxml
  bs4
*comandos para instalar:
  pip install lxml bs4
  pip3 install lxml bs4

'''
df = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')
#lendo o arquivo html de um site
display(df) #retorna uma lista

[                         Bank NameBank       CityCity StateSt  CertCert  \
 0                        Citizens Bank       Sac City      IA      8758
 1             Heartland Tri-State Bank        Elkhart      KS     25851
 2                  First Republic Bank  San Francisco      CA     59017
 3                       Signature Bank       New York      NY     57053
 4                  Silicon Valley Bank    Santa Clara      CA     24735
 ..                                 ...            ...     ...       ...
 563                 Superior Bank, FSB       Hinsdale      IL     32646
 564                Malta National Bank          Malta      OH      6629
 565    First Alliance Bank & Trust Co.     Manchester      NH     34264
 566  National State Bank of Metropolis     Metropolis      IL      3815
 567                   Bank of Honolulu       Honolulu      HI     21029

                  Acquiring InstitutionAI Closing DateClosing  FundFund
 0              Iowa Trust & Savings Bank    November 3, 2023     10545
 1                 Dream First Bank, N.A.       July 28, 2023     10544
 2              JPMorgan Chase Bank, N.A.         May 1, 2023     10543
 3                    Flagstar Bank, N.A.      March 12, 2023     10540
 4    First–Citizens Bank & Trust Company      March 10, 2023     10539
 ..                                   ...                 ...       ...
 563                Superior Federal, FSB       July 27, 2001      6004
 564                    North Valley Bank         May 3, 2001      4648
 565  Southern New Hampshire Bank & Trust    February 2, 2001      4647
 566              Banterra Bank of Marion   December 14, 2000      4646
 567                   Bank of the Orient    October 13, 2000      4645

 [568 rows x 7 columns]]

#_Indexação de DataFrames:_

In [6]:
df2 = pd.DataFrame({"Peso": [72,80,60],"Altura": [180,170,165], "Idade": [26,19,15]})
display(df2)

   Peso  Altura  Idade
0    72     180     26
1    80     170     19
2    60     165     15

In [7]:
#Outra Forma
dados = np.array([[72,180,26],[80,170,19],[60,165,15]])
df2 = pd.DataFrame(data = dados, columns = ['Peso', 'Altura', 'Idade'], index = [1,2,3]) #Ja mudando os indices
display(df2)

   Peso  Altura  Idade
1    72     180     26
2    80     170     19
3    60     165     15

In [8]:
#acessando elemento específico
df2.loc[1, 'Peso'] #linha x coluna
#Acessa o dado do indice 1 da colunas Peso

72

In [9]:
df2[['Peso', 'Altura']] #Acessando dados de duas colunas

   Peso  Altura
1    72     180
2    80     170
3    60     165

In [16]:
print(df2.iloc[2,1]) #df.iloc[2][1]
#acessando dados pelo indice e pela posição da colunas por valores numéricos

165

In [17]:
df['W']

A    1.800547
B   -1.991113
C   -0.464219
D    1.070506
E   -2.065656
Name: W, dtype: float64

In [18]:
df['new'] = df['W'] #crio uma colunsa chamada new e add os valores da colunas W nela
df

          W         X         Y         Z       new
A  1.800547 -0.709049 -0.007075  0.953310  1.800547
B -1.991113 -0.084868  0.326863 -0.312534 -1.991113
C -0.464219  0.007974  0.882472  1.220398 -0.464219
D  1.070506 -0.520674  0.730661  1.305201  1.070506
E -2.065656 -1.173851 -0.175555 -0.857468 -2.065656

In [19]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  1.800547 -0.709049 -0.007075  0.953310  1.793472
B -1.991113 -0.084868  0.326863 -0.312534 -1.664250
C -0.464219  0.007974  0.882472  1.220398  0.418252
D  1.070506 -0.520674  0.730661  1.305201  1.801167
E -2.065656 -1.173851 -0.175555 -0.857468 -2.241211

#_Funções importantes:_

In [20]:
df.drop('new', axis = 1, inplace = True) #estou excluindo a colunas 'new', logo coloco o axis como 1
#Uso o inplace para garantir que meu df seja afetado, caso contrário essas modificações não iriam para ele
df

          W         X         Y         Z
A  1.800547 -0.709049 -0.007075  0.953310
B -1.991113 -0.084868  0.326863 -0.312534
C -0.464219  0.007974  0.882472  1.220398
D  1.070506 -0.520674  0.730661  1.305201
E -2.065656 -1.173851 -0.175555 -0.857468

In [21]:
df.loc['A'] #valores do indice A

W    1.800547
X   -0.709049
Y   -0.007075
Z    0.953310
Name: A, dtype: float64

In [22]:
df.loc[['A', 'B']] #selecionando duas linhas

          W         X         Y         Z
A  1.800547 -0.709049 -0.007075  0.953310
B -1.991113 -0.084868  0.326863 -0.312534

In [23]:
df.iloc[0,2] #A e Y

-0.007074781629256243

#_Estudando melhor o Iloc e Filtros:_

In [24]:
df.loc[['A', 'B'], 'W']

A    1.800547
B   -1.991113
Name: W, dtype: float64

In [25]:
df.loc[['A' , 'B'], ['W', 'Y']]

          W         Y
A  1.800547 -0.007075
B -1.991113  0.326863

In [26]:
df.iloc[: -1] #do 0 até o último valor

          W         X         Y         Z
A  1.800547 -0.709049 -0.007075  0.953310
B -1.991113 -0.084868  0.326863 -0.312534
C -0.464219  0.007974  0.882472  1.220398
D  1.070506 -0.520674  0.730661  1.305201

In [27]:
df.iloc[1:4]

          W         X         Y         Z
B -1.991113 -0.084868  0.326863 -0.312534
C -0.464219  0.007974  0.882472  1.220398
D  1.070506 -0.520674  0.730661  1.305201

In [28]:
#Seleção Condicionais (Máscaras)
df > 0

       W      X      Y      Z
A   True  False  False   True
B  False  False   True  False
C  False   True   True   True
D   True  False   True   True
E  False  False  False  False

In [29]:
df[df > 0] #retornou apenas valores maiores que 0

          W         X         Y         Z
A  1.800547       NaN       NaN  0.953310
B       NaN       NaN  0.326863       NaN
C       NaN  0.007974  0.882472  1.220398
D  1.070506       NaN  0.730661  1.305201
E       NaN       NaN       NaN       NaN

In [30]:
df[df['Y'] > 0] #retornando os indices em que na colunas Y é maior que zero

          W         X         Y         Z
B -1.991113 -0.084868  0.326863 -0.312534
C -0.464219  0.007974  0.882472  1.220398
D  1.070506 -0.520674  0.730661  1.305201

In [31]:
df[(df['Y'] > 0) & (df['W'] > 0)] #Retorna os indices que a colunas Y e W são maiores que zero

          W         X         Y         Z
D  1.070506 -0.520674  0.730661  1.305201

#_Operações com índices:_

In [63]:
#algumas funções interessantes
print(df.index)
print(df.columns)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [64]:
df.reset_index(inplace = True) #Reseta os índices do meu df
#cria uma coluna com os valores antigos
#obs! para alterar o df tenho que colocar o inplace = True
df

  index         W         X         Y         Z
0     A  0.194534 -0.121365  0.745119 -0.725044
1     B -0.531893 -1.079807 -0.988132  1.425870
2     C -0.783987  0.254527 -1.996077 -0.110237
3     D  0.747088 -0.779894 -0.941424 -0.527928
4     E -0.218164  1.982982  1.039475  0.450998

In [65]:
df.set_index("index", inplace = True) # coloco para a coluna index virar os indíces

In [66]:
df

              W         X         Y         Z
index
A      0.194534 -0.121365  0.745119 -0.725044
B     -0.531893 -1.079807 -0.988132  1.425870
C     -0.783987  0.254527 -1.996077 -0.110237
D      0.747088 -0.779894 -0.941424 -0.527928
E     -0.218164  1.982982  1.039475  0.450998

In [67]:
novo_index = 'CA NY WY OR CO'.split()
df['novo_index'] = novo_index
df

              W         X         Y         Z novo_index
index
A      0.194534 -0.121365  0.745119 -0.725044         CA
B     -0.531893 -1.079807 -0.988132  1.425870         NY
C     -0.783987  0.254527 -1.996077 -0.110237         WY
D      0.747088 -0.779894 -0.941424 -0.527928         OR
E     -0.218164  1.982982  1.039475  0.450998         CO

In [71]:
#df.set_index("novo_index", inplace = True)
#df #excluiu o antigo indíce!
#O certo é da seguinte forma:
df.reset_index().set_index("novo_index")

           index         W         X         Y         Z
novo_index
CA             A  0.194534 -0.121365  0.745119 -0.725044
NY             B -0.531893 -1.079807 -0.988132  1.425870
WY             C -0.783987  0.254527 -1.996077 -0.110237
OR             D  0.747088 -0.779894 -0.941424 -0.527928
CO             E -0.218164  1.982982  1.039475  0.450998

#_Índices Multiníveis:_

In [75]:
outside = 'G1 G1 G1 G2 G2 G2'.split()
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside)) #junta as duas listas criando uma dupla, logo criamos uma lista de duplas

In [77]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [78]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [82]:
df = pd.DataFrame(randn(6,2), index = hier_index, columns = ['A', 'B'])
df

             A         B
G1 1 -1.179530  1.557615
   2 -0.537864 -0.342189
   3 -0.358455 -0.732832
G2 1  0.950297 -0.403197
   2  0.571872  0.266320
   3  0.567198  0.200694

In [87]:
df.loc["G1"].loc[:]

          A         B
1 -1.179530  1.557615
2 -0.537864 -0.342189
3 -0.358455 -0.732832

In [88]:
df.index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [89]:
df.index.names

FrozenList([None, None])

In [91]:
df.index.names = ["Grupos", "Número"]
df

                      A         B
Grupos Número
G1     1      -1.179530  1.557615
       2      -0.537864 -0.342189
       3      -0.358455 -0.732832
G2     1       0.950297 -0.403197
       2       0.571872  0.266320
       3       0.567198  0.200694

In [93]:
#Utilizando o xs
df.xs(1, level = "Número") #procuro os indices de número 1 no level Número

               A         B
Grupos
G1     -1.179530  1.557615
G2      0.950297 -0.403197

#_Tratando dados ausentes:_

In [95]:
df= pd.DataFrame({'A': [1,2,np.nan],
                  "B": [5,np.nan, np.nan],
                  'C' : [1,2,3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [102]:
#Usando o dropna
df.dropna(axis = 0) #jogo fora as linhas

     A    B  C
0  1.0  5.0  1

In [100]:
df.dropna(axis = 1) #jogo fora as colunas

   C
0  1
1  2
2  3

In [101]:
df.dropna(thresh = 2, axis = 1) #sempre que encontrar 2 ou mais valores ausentes descarto

     A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [105]:
#Usando o fillna (preencher o valores ausentes)
df.fillna("Conteúdo")

          A         B  C
0       1.0       5.0  1
1       2.0  Conteúdo  2
2  Conteúdo  Conteúdo  3

In [109]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [110]:
#Usando o ffill (preenche com a última informação)
df.ffill()

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [ ]:
#Usano o bfill (é o inverso, pego a informação debaixo)
#nesse caso não vai funcionar pois há dados nulos que não possuem dados depois deles

#_Groupby:_

In [111]:
import pandas as pd
# Cria um DataFrame
data = {'Classe':['Júnior','Júnior','Pleno','Pleno','Sênior','Sênior'],
       'Nome':['Jorge','Carlos','Roberta','Patrícia','Bruno','Vera'],
       'Venda':[200,120,340,124,243,350]}
df = pd.DataFrame(data)

In [112]:
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [121]:
group = df.groupby('Classe')

In [122]:
group.sum()

<ipython-input-122-bc5acc5cee8c>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  group.sum()

        Venda
Classe
Júnior    320
Pleno     464
Sênior    593

In [123]:
group.mean()

<ipython-input-123-8034d52793c2>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  group.mean()

        Venda
Classe
Júnior  160.0
Pleno   232.0
Sênior  296.5

In [125]:
df.groupby(df['Classe']).mean()

<ipython-input-125-baa6776f6dd1>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(df['Classe']).mean()

        Venda
Classe
Júnior  160.0
Pleno   232.0
Sênior  296.5

In [126]:
df.groupby(df['Classe']).min()

            Nome  Venda
Classe
Júnior    Carlos    120
Pleno   Patrícia    124
Sênior     Bruno    243

In [128]:
df.groupby(df['Classe']).max()

           Nome  Venda
Classe
Júnior    Jorge    200
Pleno   Roberta    340
Sênior     Vera    350

In [132]:
df2 = df.copy() #se eu não usar o .copy eu crio um ponteiro que altera o df
df2

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [148]:
df2['Venda'] = [150,432,190,230,410,155]
df2

   Classe      Nome  Venda
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patrícia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [150]:
df2

   Classe      Nome  Venda
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patrícia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [151]:
df3 = pd.concat([df,df2])
df3

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patrícia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [152]:
df3.groupby(['Classe', 'Nome']).sum()

                 Venda
Classe Nome
Júnior Carlos      552
       Jorge       350
Pleno  Patrícia    354
       Roberta     530
Sênior Bruno       653
       Vera        505

#_Merge, Concat e Join:_